servconf:
  port: desired port
dbconf:
  host: PostgreSQL database host adress
  port: port
  ssl: True or False
  user: username
  password: password
  db: name
  tinput: table from third party
  tuni: table to unisender api
  tsms: table with SMS relay timed
  tports: table with sms relays ports list
  tcheck: table with sms relay not timed
uniconf:
  key: unisender api key
  pluslist: list to paste entrys from api
goipconf:
  host: GoIP relay host adress
  port: port
  user: username of admin
  password: password of admin
  simcount: number of active SIM cards in relay
  messages:
    - first message
    - second message
teleconf:
  token: telegram token
  chat: telegram chat id
senderconf:
  phone: phone number of sms receiver
  relays:
    -
      host: GoIP relay host adress
      port: port
      user: username of admin
      password: password of admin
      simcount: number of active SIM cards in relay
      messages:
        - first message
        - second message
    -
      host: GoIP relay host adress
      port: port
      user: username of admin
      password: password of admin
      simcount: number of active SIM cards in relay
      messages:
        - first message
        - second message